// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUCFNY3w97vw22oAeOOqULkwDc8l4xkVo',
    appId: '1:790265899945:web:0ef542e9e279ddb7d8b2b8',
    messagingSenderId: '790265899945',
    projectId: 'jfiit-44e3c',
    authDomain: 'jfiit-44e3c.firebaseapp.com',
    storageBucket: 'jfiit-44e3c.appspot.com',
    measurementId: 'G-7VK4QMSHPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuEZjYL_B8_jfkqEBpCYmR4DYP2b-SajU',
    appId: '1:790265899945:android:5e9f4a5259f2a9f4d8b2b8',
    messagingSenderId: '790265899945',
    projectId: 'jfiit-44e3c',
    storageBucket: 'jfiit-44e3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC28NqWH-ylefMRz74OD1Gu81t7BIe4YK8',
    appId: '1:790265899945:ios:2c4c208ecf6fb070d8b2b8',
    messagingSenderId: '790265899945',
    projectId: 'jfiit-44e3c',
    storageBucket: 'jfiit-44e3c.appspot.com',
    iosClientId: '790265899945-vk2fvtakc9psqc38115vhu65nkpppkjn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC28NqWH-ylefMRz74OD1Gu81t7BIe4YK8',
    appId: '1:790265899945:ios:2c4c208ecf6fb070d8b2b8',
    messagingSenderId: '790265899945',
    projectId: 'jfiit-44e3c',
    storageBucket: 'jfiit-44e3c.appspot.com',
    iosClientId: '790265899945-vk2fvtakc9psqc38115vhu65nkpppkjn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );
}
