// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASG4I75-PgOP1r7Mg90-Z43xdYGPBIq9M',
    appId: '1:749296617679:web:82e4b2835a525b185c4fba',
    messagingSenderId: '749296617679',
    projectId: 'fitnessapp-bf5e4',
    authDomain: 'fitnessapp-bf5e4.firebaseapp.com',
    storageBucket: 'fitnessapp-bf5e4.appspot.com',
    measurementId: 'G-FNKH40VCSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIAf8NfwE7tkg8jZOAxvb5abOfrf5ebmI',
    appId: '1:749296617679:android:753db58a94f5e3d25c4fba',
    messagingSenderId: '749296617679',
    projectId: 'fitnessapp-bf5e4',
    storageBucket: 'fitnessapp-bf5e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwfPho-zKe05fg4WiB8Ijx_9jfDJabT5A',
    appId: '1:749296617679:ios:f9b49c8e723741ab5c4fba',
    messagingSenderId: '749296617679',
    projectId: 'fitnessapp-bf5e4',
    storageBucket: 'fitnessapp-bf5e4.appspot.com',
    iosClientId: '749296617679-bh339b58mtak593jtt64afkrscrpg6cl.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwfPho-zKe05fg4WiB8Ijx_9jfDJabT5A',
    appId: '1:749296617679:ios:f9b49c8e723741ab5c4fba',
    messagingSenderId: '749296617679',
    projectId: 'fitnessapp-bf5e4',
    storageBucket: 'fitnessapp-bf5e4.appspot.com',
    iosClientId: '749296617679-bh339b58mtak593jtt64afkrscrpg6cl.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );
}
